#!/usr/bin/env bash

brew_cask_upgrade() {
	red=`tput setaf 1`
	green=`tput setaf 2`
	reset=`tput sgr0`

	casks=( $(brew cask list) )
	for cask in ${casks[@]}
	do
		version=$(brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
		installed=$(find "/usr/local/Caskroom/$cask" -maxdepth 1 -name "$version" -type d)

		if [[ -z $installed ]]; then
			echo "${red}${cask}${reset} requires ${red}update${reset}."
			(set -x; brew cask install $cask --force;)
		else
			echo "${red}${cask}${reset} is ${green}up-to-date${reset}."
		fi
	done
}

pr (){
	open-pr ${1-main}
}

_pr () {
	branches=($(git branch -r --list \*VR-\*))
	arguments=()
	for branch in "${branches[@]}"; do
		arguments+=(${branch##*/})
	done
	arguments+=("main")
	unset branches
	_values '' $arguments && ret=0
	unset arguments
}

gzip_size () {
	gzip -c $1 | wc -c
}

show-port() { lsof -i :$1; }
free-port() { kill "$(lsof -t -i :$1)"; }
kill-port() { kill -kill "$(lsof -t -i :$1)"; }

clean-branches() {
	git remote prune origin
	git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -D
}
