# disable oh my zsh auto updates
DISABLE_AUTO_UPDATE="true"

source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
	printf "$(tput setaf 7)Creating a zgen save...\033[m\n"

	zgen oh-my-zsh

	zgen oh-my-zsh lib/completion.zsh
	zgen oh-my-zsh lib/git.zsh
	zgen oh-my-zsh lib/history.zsh
	zgen oh-my-zsh lib/nvm.zsh
	zgen oh-my-zsh lib/spectrum.zsh
	zgen oh-my-zsh lib/theme-and-appearance.zsh

	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/npm
	zgen oh-my-zsh plugins/yarn

	zgen load zsh-users/zsh-completions src
	zgen load caarlos0/zsh-open-pr

	zgen load denysdovhan/spaceship-prompt spaceship

	# this must be the last loaded
	zgen load zsh-users/zsh-syntax-highlighting

  	# generate the init script from plugins above
  	zgen save
fi

# Load the shell dotfiles, and then some:
for file in ~/.{aliases,exports,functions,git-prompt}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# spaceship theme customization
SPACESHIP_TIME_SHOW=true

autoload -Uz compinit
compinit

# Fix some autocomplete options
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=31=33'
zstyle ':completion:*' special-dirs true

# This loads nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
