# disable oh my zsh auto updates
DISABLE_AUTO_UPDATE="true"

source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
	printf "$(tput setaf 7)Creating a zgen save...\033[m\n"

	zgen oh-my-zsh

	zgen oh-my-zsh lib/completion.zsh
	zgen oh-my-zsh lib/git.zsh
	zgen oh-my-zsh lib/history.zsh
	zgen oh-my-zsh lib/spectrum.zsh
	zgen oh-my-zsh lib/theme-and-appearance.zsh

	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/npm
	zgen oh-my-zsh plugins/yarn

	zgen load zsh-users/zsh-completions src
	zgen load caarlos0/zsh-open-pr

	zgen load denysdovhan/spaceship-prompt spaceship

	# this must be the last loaded
	zgen load zsh-users/zsh-syntax-highlighting

  	# generate the init script from plugins above
  	zgen save
fi

# Load the shell dotfiles, and then some:
for file in ~/.{aliases,exports,functions,git-prompt}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# spaceship theme customization
SPACESHIP_TIME_SHOW=true

SPACESHIP_PROMPT_ORDER=(
	time
	user
	dir
	host
	git
	# hg
	# package
	node
	# ruby
	# elixir
	# xcode
	# swift
	# golang
	# php
	# rust
	# haskell
	# julia
	docker
	# aws
	# venv
	# conda
	# pyenv
	# dotnet
	# ember
	# kubectl
	exec_time
	line_sep
	battery
	# vi_mode
	# jobs
	exit_code
	char
)

eval "$(fnm env --use-on-cd)"

autoload -Uz compinit
compinit

# Fix some autocomplete options
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=31=33'
zstyle ':completion:*' special-dirs true

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source <(kubectl completion zsh)


# Load Angular CLI autocompletion.
source <(ng completion script)

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/dom/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/dom/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/dom/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/dom/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# bun completions
[ -s "/Users/dom/.bun/_bun" ] && source "/Users/dom/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
