# disable oh my zsh auto updates
DISABLE_AUTO_UPDATE="true"

source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
	printf "$(tput setaf 7)Creating a zgen save...\033[m\n"

	zgen oh-my-zsh

	zgen oh-my-zsh lib/completion.zsh
	zgen oh-my-zsh lib/git.zsh
	zgen oh-my-zsh lib/history.zsh
	zgen oh-my-zsh lib/spectrum.zsh
	zgen oh-my-zsh lib/theme-and-appearance.zsh

	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/virtualenvwrapper
	zgen oh-my-zsh plugins/python
	zgen oh-my-zsh plugins/mvn
	zgen oh-my-zsh plugins/npm
	zgen oh-my-zsh plugins/yarn

	zgen load zsh-users/zsh-completions src
	zgen load caarlos0/zsh-open-pr

	# this must be the last loaded
	zgen load zsh-users/zsh-syntax-highlighting

  	# generate the init script from plugins above
  	zgen save
fi

source ~/.exports
source ~/.functions

autoload -Uz compinit
compinit

# Fix some autocomplete options
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=31=33'
zstyle ':completion:*' special-dirs true

# The next line updates PATH for the Google Cloud SDK.
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
# The next line enables shell command completion for gcloud.
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# trick: the virtualenvwrapper zsh plugin activate the env when a cd
# command is executed. If I open a shell directly into a python directory
# the venv is not activated, so... :D
cd .
